server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Redireciona tudo para o index.html (necessário para SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache para assets estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
